// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: telemetry.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`                        // Unique UUID generated by the sender
	SenderPublicKey string                 `protobuf:"bytes,2,opt,name=sender_public_key,json=senderPublicKey,proto3" json:"sender_public_key,omitempty"` // The full identity of the sender
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                          // The message payload
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // Unix timestamp (milliseconds)
	Latitude        float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	HopCount        int32                  `protobuf:"varint,7,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"` // How many nodes this passed through
	Rssi            int32                  `protobuf:"varint,8,opt,name=rssi,proto3" json:"rssi,omitempty"`                         // Signal strength at the last hop
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshReport) Reset() {
	*x = MeshReport{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshReport) ProtoMessage() {}

func (x *MeshReport) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshReport.ProtoReflect.Descriptor instead.
func (*MeshReport) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *MeshReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *MeshReport) GetSenderPublicKey() string {
	if x != nil {
		return x.SenderPublicKey
	}
	return ""
}

func (x *MeshReport) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MeshReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MeshReport) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MeshReport) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MeshReport) GetHopCount() int32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *MeshReport) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

type ReportBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentity  string                 `protobuf:"bytes,1,opt,name=node_identity,json=nodeIdentity,proto3" json:"node_identity,omitempty"`
	Reports       []*MeshReport          `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportBatch) Reset() {
	*x = ReportBatch{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBatch) ProtoMessage() {}

func (x *ReportBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBatch.ProtoReflect.Descriptor instead.
func (*ReportBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ReportBatch) GetNodeIdentity() string {
	if x != nil {
		return x.NodeIdentity
	}
	return ""
}

func (x *ReportBatch) GetReports() []*MeshReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type NodeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,2,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *NodeIdentity) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodeIdentity) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *NodeIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type NetworkStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActiveNodesCount    int32                  `protobuf:"varint,1,opt,name=active_nodes_count,json=activeNodesCount,proto3" json:"active_nodes_count,omitempty"`
	TotalReportsRelayed int32                  `protobuf:"varint,2,opt,name=total_reports_relayed,json=totalReportsRelayed,proto3" json:"total_reports_relayed,omitempty"`
	SystemAlert         string                 `protobuf:"bytes,3,opt,name=system_alert,json=systemAlert,proto3" json:"system_alert,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatus.ProtoReflect.Descriptor instead.
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkStatus) GetActiveNodesCount() int32 {
	if x != nil {
		return x.ActiveNodesCount
	}
	return 0
}

func (x *NetworkStatus) GetTotalReportsRelayed() int32 {
	if x != nil {
		return x.TotalReportsRelayed
	}
	return 0
}

func (x *NetworkStatus) GetSystemAlert() string {
	if x != nil {
		return x.SystemAlert
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\xf8\x01\n" +
	"\n" +
	"MeshReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12*\n" +
	"\x11sender_public_key\x18\x02 \x01(\tR\x0fsenderPublicKey\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\thop_count\x18\a \x01(\x05R\bhopCount\x12\x12\n" +
	"\x04rssi\x18\b \x01(\x05R\x04rssi\"c\n" +
	"\vReportBatch\x12#\n" +
	"\rnode_identity\x18\x01 \x01(\tR\fnodeIdentity\x12/\n" +
	"\areports\x18\x02 \x03(\v2\x15.telemetry.MeshReportR\areports\"j\n" +
	"\fNodeIdentity\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12!\n" +
	"\fdevice_model\x18\x02 \x01(\tR\vdeviceModel\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"h\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"\x94\x01\n" +
	"\rNetworkStatus\x12,\n" +
	"\x12active_nodes_count\x18\x01 \x01(\x05R\x10activeNodesCount\x122\n" +
	"\x15total_reports_relayed\x18\x02 \x01(\x05R\x13totalReportsRelayed\x12!\n" +
	"\fsystem_alert\x18\x03 \x01(\tR\vsystemAlert2\xe4\x01\n" +
	"\rMeshTelemetry\x12C\n" +
	"\fSubmitReport\x12\x15.telemetry.MeshReport\x1a\x1c.telemetry.TelemetryResponse\x12A\n" +
	"\tSyncBatch\x12\x16.telemetry.ReportBatch\x1a\x1c.telemetry.TelemetryResponse\x12K\n" +
	"\x14StreamNetworkUpdates\x12\x17.telemetry.NodeIdentity\x1a\x18.telemetry.NetworkStatus0\x01B-\n" +
	"\x18com.example.findnet.grpcP\x01Z\x0f./internal/grpcb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_telemetry_proto_goTypes = []any{
	(*MeshReport)(nil),        // 0: telemetry.MeshReport
	(*ReportBatch)(nil),       // 1: telemetry.ReportBatch
	(*NodeIdentity)(nil),      // 2: telemetry.NodeIdentity
	(*TelemetryResponse)(nil), // 3: telemetry.TelemetryResponse
	(*NetworkStatus)(nil),     // 4: telemetry.NetworkStatus
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.ReportBatch.reports:type_name -> telemetry.MeshReport
	0, // 1: telemetry.MeshTelemetry.SubmitReport:input_type -> telemetry.MeshReport
	1, // 2: telemetry.MeshTelemetry.SyncBatch:input_type -> telemetry.ReportBatch
	2, // 3: telemetry.MeshTelemetry.StreamNetworkUpdates:input_type -> telemetry.NodeIdentity
	3, // 4: telemetry.MeshTelemetry.SubmitReport:output_type -> telemetry.TelemetryResponse
	3, // 5: telemetry.MeshTelemetry.SyncBatch:output_type -> telemetry.TelemetryResponse
	4, // 6: telemetry.MeshTelemetry.StreamNetworkUpdates:output_type -> telemetry.NetworkStatus
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
